base_url = "https://pert.dev"
title = "pert.dev"
theme = "apollo"
description = "Pert's personal site"
build_search_index = false
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"              # light, dark, auto, toggle
fancy_code = true
dynamic_note = true           # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true

menu = [
    { name = "/posts", url = "/posts", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "twitter", url = "https://twitter.com/rupert648", icon = "twitter" },
    { name = "github", url = "https://github.com/rupert648/", icon = "github" },
    { name = "coffee", url = "https://buymeacoffee.com/rupertcarr", icon = "coffee" },
]
