name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Install Zola
        if: contains(steps.changed-files.outputs.all_changed_files, 'blog/')
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      - name: Build Zola site
        if: contains(steps.changed-files.outputs.all_changed_files, 'blog/')
        run: cd blog && zola build

      - name: Install Rust toolchain
        if: contains(steps.changed-files.outputs.all_changed_files, 'services/backend')
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Backend Rust Server
        if: contains(steps.changed-files.outputs.all_changed_files, 'services/backend')
        run: cd services/backend && cargo build --release
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          
      - name: Deploy
        env:
          HOST: ${{ secrets.LINODE_HOST }}
          USER: ${{ secrets.LINODE_USER }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh "$CHANGED_FILES"
