name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Get PR number
        id: pr
        run: echo "PR_NUMBER=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
      
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1

      # We need to update this so the base links in zola point to the right place
      - name: Update base_url in config
        run: |
          sed -i "s|base_url = \"https://pert.dev\"|base_url = \"https://pr-${{ github.event.pull_request.number }}.pert.dev\"|" blog/config.toml

      - name: Build Zola site
        run: cd blog && zola build
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          
      - name: Deploy Preview
        env:
          HOST: ${{ secrets.LINODE_HOST }}
          USER: ${{ secrets.LINODE_USER }}
          PREVIEW_ID: ${{ steps.pr.outputs.PR_NUMBER }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          chmod +x ./scripts/preview.sh
          ./scripts/preview.sh

      - name: Comment PR
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = `https://pr-${context.issue.number}.pert.dev`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment is ready!\n\nPreview URL: ${previewUrl}`
            });
